import React from 'react';
declare const _default: {
    Value: typeof import("./nodes/AnimatedValue").default;
    ValueXY: typeof import("./nodes/AnimatedValueXY").default;
    Interpolation: typeof import("./nodes/AnimatedInterpolation").default;
    Node: typeof import("./nodes/AnimatedNode").default;
    decay: (value: import("./nodes/AnimatedValue").default | import("./nodes/AnimatedValueXY").default, config: import("./animations/DecayAnimation").DecayAnimationConfig) => import("./AnimatedMock").CompositeAnimation;
    timing: (value: import("./nodes/AnimatedValue").default | import("./nodes/AnimatedValueXY").default, config: import("./animations/TimingAnimation").TimingAnimationConfig) => import("./AnimatedMock").CompositeAnimation;
    spring: (value: import("./nodes/AnimatedValue").default | import("./nodes/AnimatedValueXY").default, config: import("./animations/SpringAnimation").SpringAnimationConfig) => import("./AnimatedMock").CompositeAnimation;
    add: (a: number | import("./nodes/AnimatedNode").default, b: number | import("./nodes/AnimatedNode").default) => import("./nodes/AnimatedAddition").default;
    subtract: (a: number | import("./nodes/AnimatedNode").default, b: number | import("./nodes/AnimatedNode").default) => import("./nodes/AnimatedSubtraction").default;
    divide: (a: number | import("./nodes/AnimatedNode").default, b: number | import("./nodes/AnimatedNode").default) => import("./nodes/AnimatedDivision").default;
    multiply: (a: number | import("./nodes/AnimatedNode").default, b: number | import("./nodes/AnimatedNode").default) => import("./nodes/AnimatedMultiplication").default;
    modulo: (a: import("./nodes/AnimatedNode").default, modulus: number) => import("./nodes/AnimatedModulo").default;
    diffClamp: (a: import("./nodes/AnimatedNode").default, min: number, max: number) => import("./nodes/AnimatedDiffClamp").default;
    delay: (time: number) => import("./AnimatedMock").CompositeAnimation;
    sequence: (animations: import("./AnimatedMock").CompositeAnimation[]) => import("./AnimatedMock").CompositeAnimation;
    parallel: (animations: import("./AnimatedMock").CompositeAnimation[], config?: {
        stopTogether?: boolean | undefined;
    } | null | undefined) => import("./AnimatedMock").CompositeAnimation;
    stagger: (time: number, animations: import("./AnimatedMock").CompositeAnimation[]) => import("./AnimatedMock").CompositeAnimation;
    loop: (animation: import("./AnimatedMock").CompositeAnimation, { iterations }?: {
        iterations: number;
        resetBeforeIteration?: boolean | undefined;
    }) => import("./AnimatedMock").CompositeAnimation;
    event: (argMapping: (import("./nodes/AnimatedValue").default | {
        [key: string]: import("./AnimatedEvent").Mapping;
    } | null | undefined)[], config: import("./AnimatedEvent").EventConfig) => any;
    createAnimatedComponent: typeof import("./createAnimatedComponent").default;
    attachNativeEvent: any;
    forkEvent: (event: import("./AnimatedEvent").AnimatedEvent | ((...args: any) => any) | null | undefined, listener: (...args: any) => any) => import("./AnimatedEvent").AnimatedEvent | ((...args: any) => any);
    unforkEvent: (event: import("./AnimatedEvent").AnimatedEvent | ((...args: any) => any) | null | undefined, listener: (...args: any) => any) => void;
    Event: any;
    __PropsOnlyForTests: typeof import("./nodes/AnimatedProps").default;
    FlatList: any;
    Image: any;
    ScrollView: any;
    SectionList: any;
    Text: any;
    View: React.AbstractComponent<{
        readonly " Thou shalt ignore this here prop or risketh a runtime mad as a bag of ferrets."?: any;
        readonly onBlur?: any;
        readonly onFocus?: any;
        readonly onAccessibilityAction?: any;
        readonly onAccessibilityTap?: any;
        readonly onLayout?: any;
        readonly onMagicTap?: any;
        readonly onAccessibilityEscape?: any;
        readonly onMoveShouldSetResponder?: any;
        readonly onMoveShouldSetResponderCapture?: any;
        readonly onResponderGrant?: any;
        readonly onResponderMove?: any;
        readonly onResponderReject?: any;
        readonly onResponderRelease?: any;
        readonly onResponderStart?: any;
        readonly onResponderEnd?: any;
        readonly onResponderTerminate?: any;
        readonly onResponderTerminationRequest?: any;
        readonly onStartShouldSetResponder?: any;
        readonly onStartShouldSetResponderCapture?: any;
        readonly onMouseEnter?: any;
        readonly onMouseLeave?: any;
        readonly onTouchCancel?: any;
        readonly onTouchCancelCapture?: any;
        readonly onTouchEnd?: any;
        readonly onTouchEndCapture?: any;
        readonly onTouchMove?: any;
        readonly onTouchMoveCapture?: any;
        readonly onTouchStart?: any;
        readonly onTouchStartCapture?: any;
        readonly nativeBackgroundAndroid?: any;
        readonly nativeForegroundAndroid?: any;
        readonly renderToHardwareTextureAndroid?: any;
        readonly collapsable?: any;
        readonly needsOffscreenAlphaCompositing?: any;
        readonly accessibilityLiveRegion?: any;
        readonly importantForAccessibility?: any;
        readonly hasTVPreferredFocus?: any;
        readonly nextFocusDown?: any;
        readonly nextFocusForward?: any;
        readonly nextFocusLeft?: any;
        readonly nextFocusRight?: any;
        readonly nextFocusUp?: any;
        readonly focusable?: any;
        readonly onClick?: any;
        readonly accessibilityIgnoresInvertColors?: any;
        readonly accessibilityViewIsModal?: any;
        readonly accessibilityElementsHidden?: any;
        readonly shouldRasterizeIOS?: any;
        readonly children?: any;
        readonly style?: any;
        readonly accessible?: any;
        readonly accessibilityLabel?: any;
        readonly accessibilityHint?: any;
        readonly accessibilityRole?: any;
        readonly accessibilityState?: any;
        readonly accessibilityValue?: any;
        readonly accessibilityActions?: any;
        readonly testID?: any;
        readonly nativeID?: any;
        readonly hitSlop?: any;
        readonly pointerEvents?: any;
        readonly removeClippedSubviews?: any;
    }, (import("flow-builtin-types").UniqueBranding & Readonly<import("../../Renderer/shims/ReactNativeTypes").NativeMethods> & React.ComponentMethods<import("../../Components/View/ViewPropTypes").ViewProps>) | undefined>;
};
export default _default;
