import { ClassOrType, UniqueBranding } from "flow-builtin-types";
import { $PropertyType } from "utility-types";
import _valueof_AccessibilityInfo from "./Libraries/Components/AccessibilityInfo/AccessibilityInfo";
type _typeof_AccessibilityInfo = typeof _valueof_AccessibilityInfo & UniqueBranding;
type AccessibilityInfo = ClassOrType<_typeof_AccessibilityInfo>;
import _valueof_ActivityIndicator from "./Libraries/Components/ActivityIndicator/ActivityIndicator";
type _typeof_ActivityIndicator = typeof _valueof_ActivityIndicator & UniqueBranding;
type ActivityIndicator = ClassOrType<_typeof_ActivityIndicator>;
import _valueof_Button from "./Libraries/Components/Button";
type _typeof_Button = typeof _valueof_Button & UniqueBranding;
type Button = ClassOrType<_typeof_Button>;
import _valueof_CheckBox from "./Libraries/Components/CheckBox/CheckBox";
type _typeof_CheckBox = typeof _valueof_CheckBox & UniqueBranding;
type CheckBox = ClassOrType<_typeof_CheckBox>;
import _valueof_DatePickerIOS from "./Libraries/Components/DatePicker/DatePickerIOS";
type _typeof_DatePickerIOS = typeof _valueof_DatePickerIOS & UniqueBranding;
type DatePickerIOS = ClassOrType<_typeof_DatePickerIOS>;
import _valueof_DrawerLayoutAndroid from "./Libraries/Components/DrawerAndroid/DrawerLayoutAndroid";
type _typeof_DrawerLayoutAndroid = typeof _valueof_DrawerLayoutAndroid & UniqueBranding;
type DrawerLayoutAndroid = ClassOrType<_typeof_DrawerLayoutAndroid>;
import _valueof_FlatList from "./Libraries/Lists/FlatList";
type _typeof_FlatList = typeof _valueof_FlatList & UniqueBranding;
type FlatList = ClassOrType<_typeof_FlatList>;
import _valueof_Image from "./Libraries/Image/Image";
type _typeof_Image = typeof _valueof_Image & UniqueBranding;
type Image = ClassOrType<_typeof_Image>;
import _valueof_ImageBackground from "./Libraries/Image/ImageBackground";
type _typeof_ImageBackground = typeof _valueof_ImageBackground & UniqueBranding;
type ImageBackground = ClassOrType<_typeof_ImageBackground>;
import _valueof_InputAccessoryView from "./Libraries/Components/TextInput/InputAccessoryView";
type _typeof_InputAccessoryView = typeof _valueof_InputAccessoryView & UniqueBranding;
type InputAccessoryView = ClassOrType<_typeof_InputAccessoryView>;
import _valueof_KeyboardAvoidingView from "./Libraries/Components/Keyboard/KeyboardAvoidingView";
type _typeof_KeyboardAvoidingView = typeof _valueof_KeyboardAvoidingView & UniqueBranding;
type KeyboardAvoidingView = ClassOrType<_typeof_KeyboardAvoidingView>;
import _valueof_MaskedViewIOS from "./Libraries/Components/MaskedView/MaskedViewIOS";
type _typeof_MaskedViewIOS = typeof _valueof_MaskedViewIOS & UniqueBranding;
type MaskedViewIOS = ClassOrType<_typeof_MaskedViewIOS>;
import _valueof_Modal from "./Libraries/Modal/Modal";
type _typeof_Modal = typeof _valueof_Modal & UniqueBranding;
type Modal = ClassOrType<_typeof_Modal>;
import _valueof_Picker from "./Libraries/Components/Picker/Picker";
type _typeof_Picker = typeof _valueof_Picker & UniqueBranding;
type Picker = ClassOrType<_typeof_Picker>;
import _valueof_PickerIOS from "./Libraries/Components/Picker/PickerIOS";
type _typeof_PickerIOS = typeof _valueof_PickerIOS & UniqueBranding;
type PickerIOS = ClassOrType<_typeof_PickerIOS>;
import _valueof_Pressable from "./Libraries/Components/Pressable/Pressable";
type _typeof_Pressable = typeof _valueof_Pressable & UniqueBranding;
type Pressable = ClassOrType<_typeof_Pressable>;
import _valueof_ProgressBarAndroid from "./Libraries/Components/ProgressBarAndroid/ProgressBarAndroid";
type _typeof_ProgressBarAndroid = typeof _valueof_ProgressBarAndroid & UniqueBranding;
type ProgressBarAndroid = ClassOrType<_typeof_ProgressBarAndroid>;
import _valueof_ProgressViewIOS from "./Libraries/Components/ProgressViewIOS/ProgressViewIOS";
type _typeof_ProgressViewIOS = typeof _valueof_ProgressViewIOS & UniqueBranding;
type ProgressViewIOS = ClassOrType<_typeof_ProgressViewIOS>;
import _valueof_SafeAreaView from "./Libraries/Components/SafeAreaView/SafeAreaView";
type _typeof_SafeAreaView = typeof _valueof_SafeAreaView & UniqueBranding;
type SafeAreaView = ClassOrType<_typeof_SafeAreaView>;
import _valueof_ScrollView from "./Libraries/Components/ScrollView/ScrollView";
type _typeof_ScrollView = typeof _valueof_ScrollView & UniqueBranding;
type ScrollView = ClassOrType<_typeof_ScrollView>;
import _valueof_SectionList from "./Libraries/Lists/SectionList";
type _typeof_SectionList = typeof _valueof_SectionList & UniqueBranding;
type SectionList = ClassOrType<_typeof_SectionList>;
import _valueof_SegmentedControlIOS from "./Libraries/Components/SegmentedControlIOS/SegmentedControlIOS";
type _typeof_SegmentedControlIOS = typeof _valueof_SegmentedControlIOS & UniqueBranding;
type SegmentedControlIOS = ClassOrType<_typeof_SegmentedControlIOS>;
import _valueof_Slider from "./Libraries/Components/Slider/Slider";
type _typeof_Slider = typeof _valueof_Slider & UniqueBranding;
type Slider = ClassOrType<_typeof_Slider>;
import _valueof_Switch from "./Libraries/Components/Switch/Switch";
type _typeof_Switch = typeof _valueof_Switch & UniqueBranding;
type Switch = ClassOrType<_typeof_Switch>;
import _valueof_RefreshControl from "./Libraries/Components/RefreshControl/RefreshControl";
type _typeof_RefreshControl = typeof _valueof_RefreshControl & UniqueBranding;
type RefreshControl = ClassOrType<_typeof_RefreshControl>;
import _valueof_StatusBar from "./Libraries/Components/StatusBar/StatusBar";
type _typeof_StatusBar = typeof _valueof_StatusBar & UniqueBranding;
type StatusBar = ClassOrType<_typeof_StatusBar>;
import _valueof_Text from "./Libraries/Text/Text";
type _typeof_Text = typeof _valueof_Text & UniqueBranding;
type Text = ClassOrType<_typeof_Text>;
import _valueof_TextInput from "./Libraries/Components/TextInput/TextInput";
type _typeof_TextInput = typeof _valueof_TextInput & UniqueBranding;
type TextInput = ClassOrType<_typeof_TextInput>;
import _valueof_Touchable from "./Libraries/Components/Touchable/Touchable";
type _typeof_Touchable = typeof _valueof_Touchable & UniqueBranding;
type Touchable = ClassOrType<_typeof_Touchable>;
import _valueof_TouchableHighlight from "./Libraries/Components/Touchable/TouchableHighlight";
type _typeof_TouchableHighlight = typeof _valueof_TouchableHighlight & UniqueBranding;

type TouchableHighlight = ClassOrType<_typeof_TouchableHighlight>;

import _valueof_TouchableNativeFeedback from "./Libraries/Components/Touchable/TouchableNativeFeedback";
type _typeof_TouchableNativeFeedback = typeof _valueof_TouchableNativeFeedback & UniqueBranding;

type TouchableNativeFeedback = ClassOrType<_typeof_TouchableNativeFeedback>;
import _valueof_TouchableOpacity from "./Libraries/Components/Touchable/TouchableOpacity";
type _typeof_TouchableOpacity = typeof _valueof_TouchableOpacity & UniqueBranding;
type TouchableOpacity = ClassOrType<_typeof_TouchableOpacity>;
import _valueof_TouchableWithoutFeedback from "./Libraries/Components/Touchable/TouchableWithoutFeedback";
type _typeof_TouchableWithoutFeedback = typeof _valueof_TouchableWithoutFeedback & UniqueBranding;
type TouchableWithoutFeedback = ClassOrType<_typeof_TouchableWithoutFeedback>;
import _valueof_View from "./Libraries/Components/View/View";
type _typeof_View = typeof _valueof_View & UniqueBranding;
type View = ClassOrType<_typeof_View>;
import _valueof_VirtualizedList from "./Libraries/Lists/VirtualizedList";
type _typeof_VirtualizedList = typeof _valueof_VirtualizedList & UniqueBranding;
type VirtualizedList = ClassOrType<_typeof_VirtualizedList>;
import _valueof_VirtualizedSectionList from "./Libraries/Lists/VirtualizedSectionList";
type _typeof_VirtualizedSectionList = typeof _valueof_VirtualizedSectionList & UniqueBranding;
type VirtualizedSectionList = ClassOrType<_typeof_VirtualizedSectionList>;
import _valueof_ActionSheetIOS from "./Libraries/ActionSheetIOS/ActionSheetIOS";
type _typeof_ActionSheetIOS = typeof _valueof_ActionSheetIOS & UniqueBranding;
type ActionSheetIOS = ClassOrType<_typeof_ActionSheetIOS>;
import _valueof_Alert from "./Libraries/Alert/Alert";
type _typeof_Alert = typeof _valueof_Alert & UniqueBranding;
type Alert = ClassOrType<_typeof_Alert>;
import _valueof_Animated from "./Libraries/Animated/src/Animated";
type _typeof_Animated = typeof _valueof_Animated & UniqueBranding;
type Animated = ClassOrType<_typeof_Animated>;
import _valueof_Appearance from "./Libraries/Utilities/Appearance";
type _typeof_Appearance = typeof _valueof_Appearance & UniqueBranding;
type Appearance = ClassOrType<_typeof_Appearance>;
import _valueof_AppRegistry from "./Libraries/ReactNative/AppRegistry";
type _typeof_AppRegistry = typeof _valueof_AppRegistry & UniqueBranding;
type AppRegistry = ClassOrType<_typeof_AppRegistry>;
import _valueof_AppState from "./Libraries/AppState/AppState";
type _typeof_AppState = typeof _valueof_AppState & UniqueBranding;
type AppState = ClassOrType<_typeof_AppState>;
import _valueof_AsyncStorage from "./Libraries/Storage/AsyncStorage";
type _typeof_AsyncStorage = typeof _valueof_AsyncStorage & UniqueBranding;
type AsyncStorage = ClassOrType<_typeof_AsyncStorage>;
import _valueof_BackHandler from "./Libraries/Utilities/BackHandler";
type _typeof_BackHandler = typeof _valueof_BackHandler & UniqueBranding;
type BackHandler = ClassOrType<_typeof_BackHandler>;
import _valueof_Clipboard from "./Libraries/Components/Clipboard/Clipboard";
type _typeof_Clipboard = typeof _valueof_Clipboard & UniqueBranding;
type Clipboard = ClassOrType<_typeof_Clipboard>;
import _valueof_DatePickerAndroid from "./Libraries/Components/DatePickerAndroid/DatePickerAndroid";
type _typeof_DatePickerAndroid = typeof _valueof_DatePickerAndroid & UniqueBranding;
type DatePickerAndroid = ClassOrType<_typeof_DatePickerAndroid>;
import _valueof_DeviceInfo from "./Libraries/Utilities/DeviceInfo";
type _typeof_DeviceInfo = typeof _valueof_DeviceInfo & UniqueBranding;
type DeviceInfo = ClassOrType<_typeof_DeviceInfo>;
import _valueof_DevSettings from "./Libraries/Utilities/DevSettings";
type _typeof_DevSettings = typeof _valueof_DevSettings & UniqueBranding;
type DevSettings = ClassOrType<_typeof_DevSettings>;
import _valueof_Dimensions from "./Libraries/Utilities/Dimensions";
type _typeof_Dimensions = typeof _valueof_Dimensions & UniqueBranding;
type Dimensions = ClassOrType<_typeof_Dimensions>;
import _valueof_Easing from "./Libraries/Animated/src/Easing";
type _typeof_Easing = typeof _valueof_Easing & UniqueBranding;
type Easing = ClassOrType<_typeof_Easing>;
import _valueof_ReactNative from "./Libraries/Renderer/shims/ReactNative";
type _typeof_ReactNative = typeof _valueof_ReactNative & UniqueBranding;
type ReactNative = ClassOrType<_typeof_ReactNative>;
import _valueof_I18nManager from "./Libraries/ReactNative/I18nManager";
type _typeof_I18nManager = typeof _valueof_I18nManager & UniqueBranding;
type I18nManager = ClassOrType<_typeof_I18nManager>;
import _valueof_ImagePickerIOS from "./Libraries/Image/ImagePickerIOS";
type _typeof_ImagePickerIOS = typeof _valueof_ImagePickerIOS & UniqueBranding;
type ImagePickerIOS = ClassOrType<_typeof_ImagePickerIOS>;
import _valueof_InteractionManager from "./Libraries/Interaction/InteractionManager";
type _typeof_InteractionManager = typeof _valueof_InteractionManager & UniqueBranding;
type InteractionManager = ClassOrType<_typeof_InteractionManager>;
import _valueof_Keyboard from "./Libraries/Components/Keyboard/Keyboard";
type _typeof_Keyboard = typeof _valueof_Keyboard & UniqueBranding;
type Keyboard = ClassOrType<_typeof_Keyboard>;
import _valueof_LayoutAnimation from "./Libraries/LayoutAnimation/LayoutAnimation";
type _typeof_LayoutAnimation = typeof _valueof_LayoutAnimation & UniqueBranding;
type LayoutAnimation = ClassOrType<_typeof_LayoutAnimation>;
import _valueof_Linking from "./Libraries/Linking/Linking";
type _typeof_Linking = typeof _valueof_Linking & UniqueBranding;
type Linking = ClassOrType<_typeof_Linking>;
import _valueof_NativeDialogManagerAndroid from "./Libraries/NativeModules/specs/NativeDialogManagerAndroid";
type _typeof_NativeDialogManagerAndroid = typeof _valueof_NativeDialogManagerAndroid & UniqueBranding;
type NativeDialogManagerAndroid = ClassOrType<_typeof_NativeDialogManagerAndroid>;
import _valueof_NativeEventEmitter from "./Libraries/EventEmitter/NativeEventEmitter";
type _typeof_NativeEventEmitter = typeof _valueof_NativeEventEmitter & UniqueBranding;
type NativeEventEmitter = ClassOrType<_typeof_NativeEventEmitter>;
import _valueof_Networking from "./Libraries/Network/RCTNetworking";
type _typeof_Networking = typeof _valueof_Networking & UniqueBranding;
type Networking = ClassOrType<_typeof_Networking>;
import _valueof_PanResponder from "./Libraries/Interaction/PanResponder";
type _typeof_PanResponder = typeof _valueof_PanResponder & UniqueBranding;
type PanResponder = ClassOrType<_typeof_PanResponder>;
import _valueof_PermissionsAndroid from "./Libraries/PermissionsAndroid/PermissionsAndroid";
type _typeof_PermissionsAndroid = typeof _valueof_PermissionsAndroid & UniqueBranding;
type PermissionsAndroid = ClassOrType<_typeof_PermissionsAndroid>;
import _valueof_PixelRatio from "./Libraries/Utilities/PixelRatio";
type _typeof_PixelRatio = typeof _valueof_PixelRatio & UniqueBranding;
type PixelRatio = ClassOrType<_typeof_PixelRatio>;
import _valueof_PushNotificationIOS from "./Libraries/PushNotificationIOS/PushNotificationIOS";
type _typeof_PushNotificationIOS = typeof _valueof_PushNotificationIOS & UniqueBranding;
type PushNotificationIOS = ClassOrType<_typeof_PushNotificationIOS>;
import _valueof_Settings from "./Libraries/Settings/Settings";
type _typeof_Settings = typeof _valueof_Settings & UniqueBranding;
type Settings = ClassOrType<_typeof_Settings>;
import _valueof_Share from "./Libraries/Share/Share";
type _typeof_Share = typeof _valueof_Share & UniqueBranding;
type Share = ClassOrType<_typeof_Share>;
import _valueof_StatusBarIOS from "./Libraries/Components/StatusBar/StatusBarIOS";
type _typeof_StatusBarIOS = typeof _valueof_StatusBarIOS & UniqueBranding;
type StatusBarIOS = ClassOrType<_typeof_StatusBarIOS>;
import _valueof_StyleSheet from "./Libraries/StyleSheet/StyleSheet";
type _typeof_StyleSheet = typeof _valueof_StyleSheet & UniqueBranding;
type StyleSheet = ClassOrType<_typeof_StyleSheet>;
import _valueof_Systrace from "./Libraries/Performance/Systrace";
type _typeof_Systrace = typeof _valueof_Systrace & UniqueBranding;
type Systrace = ClassOrType<_typeof_Systrace>;
import _valueof_ToastAndroid from "./Libraries/Components/ToastAndroid/ToastAndroid";
type _typeof_ToastAndroid = typeof _valueof_ToastAndroid & UniqueBranding;
type ToastAndroid = ClassOrType<_typeof_ToastAndroid>;
import * as _valueof_TurboModuleRegistry from "./Libraries/TurboModule/TurboModuleRegistry";
type _typeof_TurboModuleRegistry = typeof _valueof_TurboModuleRegistry & UniqueBranding;
type TurboModuleRegistry = ClassOrType<_typeof_TurboModuleRegistry>;
import _valueof_TVEventHandler from "./Libraries/Components/AppleTV/TVEventHandler";
type _typeof_TVEventHandler = typeof _valueof_TVEventHandler & UniqueBranding;
type TVEventHandler = ClassOrType<_typeof_TVEventHandler>;
import _valueof_UIManager from "./Libraries/ReactNative/UIManager";
type _typeof_UIManager = typeof _valueof_UIManager & UniqueBranding;
type UIManager = ClassOrType<_typeof_UIManager>;
import _valueof_useColorScheme from "./Libraries/Utilities/useColorScheme";
type _typeof_useColorScheme = typeof _valueof_useColorScheme & UniqueBranding;
type useColorScheme = ClassOrType<_typeof_useColorScheme>;
import _valueof_useWindowDimensions from "./Libraries/Utilities/useWindowDimensions";
type _typeof_useWindowDimensions = typeof _valueof_useWindowDimensions & UniqueBranding;
type useWindowDimensions = ClassOrType<_typeof_useWindowDimensions>;
import _valueof_UTFSequence from "./Libraries/UTFSequence";
type _typeof_UTFSequence = typeof _valueof_UTFSequence & UniqueBranding;
type UTFSequence = ClassOrType<_typeof_UTFSequence>;
import _valueof_Vibration from "./Libraries/Vibration/Vibration";
type _typeof_Vibration = typeof _valueof_Vibration & UniqueBranding;
type Vibration = ClassOrType<_typeof_Vibration>;
import _valueof_YellowBox from "./Libraries/YellowBox/YellowBoxDeprecated";
type _typeof_YellowBox = typeof _valueof_YellowBox & UniqueBranding;
type YellowBox = ClassOrType<_typeof_YellowBox>;
import _valueof_LogBox from "./Libraries/LogBox/LogBox";
type _typeof_LogBox = typeof _valueof_LogBox & UniqueBranding;
type LogBox = ClassOrType<_typeof_LogBox>;
import _valueof_RCTDeviceEventEmitter from "./Libraries/EventEmitter/RCTDeviceEventEmitter";
type _typeof_RCTDeviceEventEmitter = typeof _valueof_RCTDeviceEventEmitter & UniqueBranding;
type RCTDeviceEventEmitter = ClassOrType<_typeof_RCTDeviceEventEmitter>;
import _valueof_RCTNativeAppEventEmitter from "./Libraries/EventEmitter/RCTNativeAppEventEmitter";
type _typeof_RCTNativeAppEventEmitter = typeof _valueof_RCTNativeAppEventEmitter & UniqueBranding;
type RCTNativeAppEventEmitter = ClassOrType<_typeof_RCTNativeAppEventEmitter>;
import _valueof_NativeModules from "./Libraries/BatchedBridge/NativeModules";
type _typeof_NativeModules = typeof _valueof_NativeModules & UniqueBranding;
type NativeModules = ClassOrType<_typeof_NativeModules>;
import _valueof_Platform from "./Libraries/Utilities/Platform";
type _typeof_Platform = typeof _valueof_Platform & UniqueBranding;
type Platform = ClassOrType<_typeof_Platform>;
import _valueof_processColor from "./Libraries/StyleSheet/processColor";
type _typeof_processColor = typeof _valueof_processColor & UniqueBranding;
type processColor = ClassOrType<_typeof_processColor>;
import _valueof_RootTagContext from "./Libraries/ReactNative/RootTagContext";
type _typeof_RootTagContext = typeof _valueof_RootTagContext & UniqueBranding;
type RootTagContext = ClassOrType<_typeof_RootTagContext>;
import _valueof_DeprecatedColorPropType from "./Libraries/DeprecatedPropTypes/DeprecatedColorPropType";
type _typeof_DeprecatedColorPropType = typeof _valueof_DeprecatedColorPropType & UniqueBranding;
type DeprecatedColorPropType = ClassOrType<_typeof_DeprecatedColorPropType>;
import _valueof_DeprecatedEdgeInsetsPropType from "./Libraries/DeprecatedPropTypes/DeprecatedEdgeInsetsPropType";
type _typeof_DeprecatedEdgeInsetsPropType = typeof _valueof_DeprecatedEdgeInsetsPropType & UniqueBranding;
type DeprecatedEdgeInsetsPropType = ClassOrType<_typeof_DeprecatedEdgeInsetsPropType>;
import _valueof_DeprecatedPointPropType from "./Libraries/DeprecatedPropTypes/DeprecatedPointPropType";
type _typeof_DeprecatedPointPropType = typeof _valueof_DeprecatedPointPropType & UniqueBranding;
type DeprecatedPointPropType = ClassOrType<_typeof_DeprecatedPointPropType>;
import _valueof_DeprecatedViewPropTypes from "./Libraries/DeprecatedPropTypes/DeprecatedViewPropTypes";
type _typeof_DeprecatedViewPropTypes = typeof _valueof_DeprecatedViewPropTypes & UniqueBranding;
type DeprecatedViewPropTypes = ClassOrType<_typeof_DeprecatedViewPropTypes>;
import { HostComponent as _HostComponentInternal } from "./Libraries/Renderer/shims/ReactNativeTypes";
type HostComponent<T> = _HostComponentInternal<T>;
export { HostComponent };
declare module.exports: {
  AccessibilityInfo(): AccessibilityInfo;
  ActivityIndicator(): ActivityIndicator;
  Button(): Button;
  CheckBox(): CheckBox;
  DatePickerIOS(): DatePickerIOS;
  DrawerLayoutAndroid(): DrawerLayoutAndroid;
  FlatList(): FlatList;
  Image(): Image;
  ImageBackground(): ImageBackground;
  InputAccessoryView(): InputAccessoryView;
  KeyboardAvoidingView(): KeyboardAvoidingView;
  MaskedViewIOS(): MaskedViewIOS;
  Modal(): Modal;
  Picker(): Picker;
  PickerIOS(): PickerIOS;
  Pressable(): Pressable;
  ProgressBarAndroid(): ProgressBarAndroid;
  ProgressViewIOS(): ProgressViewIOS;
  SafeAreaView(): SafeAreaView;
  ScrollView(): ScrollView;
  SectionList(): SectionList;
  SegmentedControlIOS(): SegmentedControlIOS;
  Slider(): Slider;
  Switch(): Switch;
  RefreshControl(): RefreshControl;
  StatusBar(): StatusBar;
  Text(): Text;
  TextInput(): TextInput;
  Touchable(): Touchable;
  TouchableHighlight(): TouchableHighlight;
  TouchableNativeFeedback(): TouchableNativeFeedback;
  TouchableOpacity(): TouchableOpacity;
  TouchableWithoutFeedback(): TouchableWithoutFeedback;
  View(): View;
  VirtualizedList(): VirtualizedList;
  VirtualizedSectionList(): VirtualizedSectionList;
  ActionSheetIOS(): ActionSheetIOS;
  Alert(): Alert;
  Animated(): Animated;
  Appearance(): Appearance;
  AppRegistry(): AppRegistry;
  AppState(): AppState;
  AsyncStorage(): AsyncStorage;
  BackHandler(): BackHandler;
  Clipboard(): Clipboard;
  DatePickerAndroid(): DatePickerAndroid;
  DeviceInfo(): DeviceInfo;
  DevSettings(): DevSettings;
  Dimensions(): Dimensions;
  Easing(): Easing;
  findNodeHandle(): $PropertyType<ReactNative, "findNodeHandle">;
  I18nManager(): I18nManager;
  ImagePickerIOS(): ImagePickerIOS;
  InteractionManager(): InteractionManager;
  Keyboard(): Keyboard;
  LayoutAnimation(): LayoutAnimation;
  Linking(): Linking;
  LogBox(): LogBox;
  NativeDialogManagerAndroid(): NativeDialogManagerAndroid;
  NativeEventEmitter(): NativeEventEmitter;
  Networking(): Networking;
  PanResponder(): PanResponder;
  PermissionsAndroid(): PermissionsAndroid;
  PixelRatio(): PixelRatio;
  PushNotificationIOS(): PushNotificationIOS;
  Settings(): Settings;
  Share(): Share;
  StatusBarIOS(): StatusBarIOS;
  StyleSheet(): StyleSheet;
  Systrace(): Systrace;
  ToastAndroid(): ToastAndroid;
  TurboModuleRegistry(): TurboModuleRegistry;
  TVEventHandler(): TVEventHandler;
  UIManager(): UIManager;
  unstable_batchedUpdates(): $PropertyType<ReactNative, "unstable_batchedUpdates">;
  useColorScheme(): useColorScheme;
  useWindowDimensions(): useWindowDimensions;
  UTFSequence(): UTFSequence;
  Vibration(): Vibration;
  YellowBox(): YellowBox;
  DeviceEventEmitter(): RCTDeviceEventEmitter;
  NativeAppEventEmitter(): RCTNativeAppEventEmitter;
  NativeModules(): NativeModules;
  Platform(): Platform;
  processColor(): processColor;
  requireNativeComponent(): (<T>(uiViewClassName: string) => HostComponent<T>);
  unstable_RootTagContext(): RootTagContext;
  unstable_enableLogBox(): (() => void);
  ColorPropType(): DeprecatedColorPropType;
  EdgeInsetsPropType(): DeprecatedEdgeInsetsPropType;
  PointPropType(): DeprecatedPointPropType;
  ViewPropTypes(): DeprecatedViewPropTypes;
}