import Button from "./Libraries/Components/Button";
import ImageBackground from "./Libraries/Image/ImageBackground";
import InputAccessoryView from "./Libraries/Components/TextInput/InputAccessoryView";
import KeyboardAvoidingView from "./Libraries/Components/Keyboard/KeyboardAvoidingView";
import Modal from "./Libraries/Modal/Modal";
import Picker from "./Libraries/Components/Picker/Picker";
import ScrollView from "./Libraries/Components/ScrollView/ScrollView";
import Switch from "./Libraries/Components/Switch/Switch";
import RefreshControl from "./Libraries/Components/RefreshControl/RefreshControl";
import StatusBar from "./Libraries/Components/StatusBar/StatusBar";
import TouchableNativeFeedback from "./Libraries/Components/Touchable/TouchableNativeFeedback";
import TouchableWithoutFeedback from "./Libraries/Components/Touchable/TouchableWithoutFeedback";
import VirtualizedList from "./Libraries/Lists/VirtualizedList";
import Alert from "./Libraries/Alert/Alert";
import Dimensions from "./Libraries/Utilities/Dimensions";
import Easing from "./Libraries/Animated/src/Easing";
import NativeEventEmitter from "./Libraries/EventEmitter/NativeEventEmitter";
import PixelRatio from "./Libraries/Utilities/PixelRatio";
import PushNotificationIOS from "./Libraries/PushNotificationIOS/PushNotificationIOS";
import Share from "./Libraries/Share/Share";
import TVEventHandler from "./Libraries/Components/AppleTV/TVEventHandler";
import { HostComponent as _HostComponentInternal } from "./Libraries/Renderer/shims/ReactNativeTypes";
export declare type HostComponent<T> = _HostComponentInternal<T>;
declare const _default: {
    readonly AccessibilityInfo: any;
    readonly ActivityIndicator: any;
    readonly Button: Button;
    readonly CheckBox: any;
    readonly DatePickerIOS: any;
    readonly DrawerLayoutAndroid: any;
    readonly FlatList: any;
    readonly Image: any;
    readonly ImageBackground: ImageBackground;
    readonly InputAccessoryView: InputAccessoryView;
    readonly KeyboardAvoidingView: KeyboardAvoidingView;
    readonly MaskedViewIOS: any;
    readonly Modal: Modal;
    readonly Picker: Picker;
    readonly PickerIOS: any;
    readonly ProgressBarAndroid: any;
    readonly ProgressViewIOS: any;
    readonly SafeAreaView: any;
    readonly ScrollView: ScrollView;
    readonly SectionList: any;
    readonly SegmentedControlIOS: any;
    readonly Slider: any;
    readonly Switch: Switch;
    readonly RefreshControl: RefreshControl;
    readonly StatusBar: StatusBar;
    readonly Text: Text;
    readonly TextInput: any;
    readonly Touchable: any;
    readonly TouchableHighlight: any;
    readonly TouchableNativeFeedback: TouchableNativeFeedback;
    readonly TouchableOpacity: any;
    readonly TouchableWithoutFeedback: TouchableWithoutFeedback;
    readonly View: any;
    readonly VirtualizedList: VirtualizedList;
    readonly VirtualizedSectionList: any;
    readonly ActionSheetIOS: any;
    readonly Alert: Alert;
    readonly Animated: any;
    readonly Appearance: any;
    readonly AppRegistry: any;
    readonly AppState: any;
    readonly AsyncStorage: any;
    readonly BackHandler: any;
    readonly Clipboard: Clipboard;
    readonly DatePickerAndroid: any;
    readonly DeviceInfo: any;
    readonly DevSettings: any;
    readonly Dimensions: Dimensions;
    readonly Easing: Easing;
    readonly findNodeHandle: any;
    readonly I18nManager: any;
    readonly ImagePickerIOS: any;
    readonly InteractionManager: any;
    readonly Keyboard: any;
    readonly LayoutAnimation: any;
    readonly Linking: any;
    readonly NativeDialogManagerAndroid: any;
    readonly NativeEventEmitter: NativeEventEmitter;
    readonly Networking: any;
    readonly PanResponder: any;
    readonly PermissionsAndroid: any;
    readonly PixelRatio: PixelRatio;
    readonly PushNotificationIOS: PushNotificationIOS;
    readonly Settings: any;
    readonly Share: Share;
    readonly StatusBarIOS: any;
    readonly StyleSheet: StyleSheet;
    readonly Systrace: any;
    readonly ToastAndroid: any;
    readonly TurboModuleRegistry: any;
    readonly TVEventHandler: TVEventHandler;
    readonly UIManager: any;
    readonly unstable_batchedUpdates: any;
    readonly useColorScheme: any;
    readonly useWindowDimensions: any;
    readonly UTFSequence: any;
    readonly Vibration: any;
    readonly YellowBox: any;
    readonly DeviceEventEmitter: any;
    readonly NativeAppEventEmitter: any;
    readonly NativeModules: any;
    readonly Platform: any;
    readonly processColor: any;
    readonly requireNativeComponent: <T>(uiViewClassName: string) => any;
    readonly unstable_RootTagContext: any;
    readonly unstable_enableLogBox: () => void;
    readonly ColorPropType: any;
    readonly EdgeInsetsPropType: any;
    readonly PointPropType: any;
    readonly ViewPropTypes: any;
};
export default _default;
