declare const ReactNativeViewAttributes: {
    UIView: {
        pointerEvents: boolean;
        accessible: boolean;
        accessibilityActions: boolean;
        accessibilityLabel: boolean;
        accessibilityLiveRegion: boolean;
        accessibilityRole: boolean;
        accessibilityState: boolean;
        accessibilityValue: boolean;
        accessibilityHint: boolean;
        importantForAccessibility: boolean;
        nativeID: boolean;
        testID: boolean;
        renderToHardwareTextureAndroid: boolean;
        shouldRasterizeIOS: boolean;
        onLayout: boolean;
        onAccessibilityAction: boolean;
        onAccessibilityTap: boolean;
        onMagicTap: boolean;
        onAccessibilityEscape: boolean;
        collapsable: boolean;
        needsOffscreenAlphaCompositing: boolean;
        style: any;
    };
    RCTView: {
        removeClippedSubviews: boolean;
        pointerEvents: boolean;
        accessible: boolean;
        accessibilityActions: boolean;
        accessibilityLabel: boolean;
        accessibilityLiveRegion: boolean;
        accessibilityRole: boolean;
        accessibilityState: boolean;
        accessibilityValue: boolean;
        accessibilityHint: boolean;
        importantForAccessibility: boolean;
        nativeID: boolean;
        testID: boolean;
        renderToHardwareTextureAndroid: boolean;
        shouldRasterizeIOS: boolean;
        onLayout: boolean;
        onAccessibilityAction: boolean;
        onAccessibilityTap: boolean;
        onMagicTap: boolean;
        onAccessibilityEscape: boolean;
        collapsable: boolean;
        needsOffscreenAlphaCompositing: boolean;
        style: any;
    };
};
export default ReactNativeViewAttributes;
