declare const ReactNativeViewAttributes: {
    UIView: {
        pointerEvents: boolean;
        accessible: boolean;
        accessibilityActions: boolean;
        accessibilityLabel: boolean;
        accessibilityLiveRegion: boolean;
        accessibilityRole: boolean;
        accessibilityState: boolean;
        accessibilityValue: boolean;
        accessibilityHint: boolean;
        importantForAccessibility: boolean;
        nativeID: boolean;
        testID: boolean;
        renderToHardwareTextureAndroid: boolean;
        shouldRasterizeIOS: boolean;
        onLayout: boolean;
        onAccessibilityAction: boolean;
        onAccessibilityTap: boolean;
        onMagicTap: boolean;
        onAccessibilityEscape: boolean;
        collapsable: boolean;
        needsOffscreenAlphaCompositing: boolean;
        style: {
            backfaceVisibility: true;
            backgroundColor: true;
            borderColor: true;
            borderTopColor: true;
            borderRightColor: true;
            borderBottomColor: true;
            borderLeftColor: true;
            borderStartColor: true;
            borderEndColor: true;
            borderRadius: true;
            borderTopLeftRadius: true;
            borderTopRightRadius: true;
            borderTopStartRadius: true;
            borderTopEndRadius: true;
            borderBottomLeftRadius: true;
            borderBottomRightRadius: true;
            borderBottomStartRadius: true;
            borderBottomEndRadius: true;
            borderStyle: true;
            borderWidth: true;
            borderTopWidth: true;
            borderRightWidth: true;
            borderBottomWidth: true;
            borderLeftWidth: true;
            opacity: true;
            elevation: true;
            transform: true;
            transformMatrix: true;
            decomposedMatrix: true;
            scaleX: true;
            scaleY: true;
            rotation: true;
            translateX: true;
            translateY: true;
            shadowColor: true;
            shadowOffset: true;
            shadowOpacity: true;
            shadowRadius: true;
            display: true;
            width: true;
            height: true;
            start: true;
            end: true;
            top: true;
            left: true;
            right: true;
            bottom: true;
            minWidth: true;
            maxWidth: true;
            minHeight: true;
            maxHeight: true;
            margin: true;
            marginVertical: true;
            marginHorizontal: true;
            marginTop: true;
            marginBottom: true;
            marginLeft: true;
            marginRight: true;
            marginStart: true;
            marginEnd: true;
            padding: true;
            paddingVertical: true;
            paddingHorizontal: true;
            paddingTop: true;
            paddingBottom: true;
            paddingLeft: true;
            paddingRight: true;
            paddingStart: true;
            paddingEnd: true;
            borderStartWidth: true;
            borderEndWidth: true;
            position: true;
            flexDirection: true;
            flexWrap: true;
            justifyContent: true;
            alignItems: true;
            alignSelf: true;
            alignContent: true;
            overflow: true;
            flex: true;
            flexGrow: true;
            flexShrink: true;
            flexBasis: true;
            aspectRatio: true;
            zIndex: true;
            direction: true;
        } & {
            color: true;
            fontFamily: true;
            fontSize: true;
            fontStyle: true;
            fontWeight: true;
            fontVariant: true;
            textShadowOffset: true;
            textShadowRadius: true;
            textShadowColor: true;
            letterSpacing: true;
            lineHeight: true;
            textAlign: true;
            textAlignVertical: true;
            includeFontPadding: true;
            textDecorationLine: true;
            textDecorationStyle: true;
            textDecorationColor: true;
            textTransform: true;
            writingDirection: true;
            backfaceVisibility: true;
            backgroundColor: true;
            borderColor: true;
            borderTopColor: true;
            borderRightColor: true;
            borderBottomColor: true;
            borderLeftColor: true;
            borderStartColor: true;
            borderEndColor: true;
            borderRadius: true;
            borderTopLeftRadius: true;
            borderTopRightRadius: true;
            borderTopStartRadius: true;
            borderTopEndRadius: true;
            borderBottomLeftRadius: true;
            borderBottomRightRadius: true;
            borderBottomStartRadius: true;
            borderBottomEndRadius: true;
            borderStyle: true;
            borderWidth: true;
            borderTopWidth: true;
            borderRightWidth: true;
            borderBottomWidth: true;
            borderLeftWidth: true;
            opacity: true;
            elevation: true;
            transform: true;
            transformMatrix: true;
            decomposedMatrix: true;
            scaleX: true;
            scaleY: true;
            rotation: true;
            translateX: true;
            translateY: true;
            shadowColor: true;
            shadowOffset: true;
            shadowOpacity: true;
            shadowRadius: true;
            display: true;
            width: true;
            height: true;
            start: true;
            end: true;
            top: true;
            left: true;
            right: true;
            bottom: true;
            minWidth: true;
            maxWidth: true;
            minHeight: true;
            maxHeight: true;
            margin: true;
            marginVertical: true;
            marginHorizontal: true;
            marginTop: true;
            marginBottom: true;
            marginLeft: true;
            marginRight: true;
            marginStart: true;
            marginEnd: true;
            padding: true;
            paddingVertical: true;
            paddingHorizontal: true;
            paddingTop: true;
            paddingBottom: true;
            paddingLeft: true;
            paddingRight: true;
            paddingStart: true;
            paddingEnd: true;
            borderStartWidth: true;
            borderEndWidth: true;
            position: true;
            flexDirection: true;
            flexWrap: true;
            justifyContent: true;
            alignItems: true;
            alignSelf: true;
            alignContent: true;
            overflow: true;
            flex: true;
            flexGrow: true;
            flexShrink: true;
            flexBasis: true;
            aspectRatio: true;
            zIndex: true;
            direction: true;
        } & {
            resizeMode: true;
            backfaceVisibility: true;
            backgroundColor: true;
            borderColor: true;
            borderWidth: true;
            borderRadius: true;
            overflow: true;
            tintColor: true;
            opacity: true;
            overlayColor: true;
            borderTopLeftRadius: true;
            borderTopRightRadius: true;
            borderBottomLeftRadius: true;
            borderBottomRightRadius: true;
            transform: true;
            transformMatrix: true;
            decomposedMatrix: true;
            scaleX: true;
            scaleY: true;
            rotation: true;
            translateX: true;
            translateY: true;
            shadowColor: true;
            shadowOffset: true;
            shadowOpacity: true;
            shadowRadius: true;
            display: true;
            width: true;
            height: true;
            start: true;
            end: true;
            top: true;
            left: true;
            right: true;
            bottom: true;
            minWidth: true;
            maxWidth: true;
            minHeight: true;
            maxHeight: true;
            margin: true;
            marginVertical: true;
            marginHorizontal: true;
            marginTop: true;
            marginBottom: true;
            marginLeft: true;
            marginRight: true;
            marginStart: true;
            marginEnd: true;
            padding: true;
            paddingVertical: true;
            paddingHorizontal: true;
            paddingTop: true;
            paddingBottom: true;
            paddingLeft: true;
            paddingRight: true;
            paddingStart: true;
            paddingEnd: true;
            borderTopWidth: true;
            borderStartWidth: true;
            borderEndWidth: true;
            borderRightWidth: true;
            borderBottomWidth: true;
            borderLeftWidth: true;
            position: true;
            flexDirection: true;
            flexWrap: true;
            justifyContent: true;
            alignItems: true;
            alignSelf: true;
            alignContent: true;
            flex: true;
            flexGrow: true;
            flexShrink: true;
            flexBasis: true;
            aspectRatio: true;
            zIndex: true;
            direction: true;
        } & {
            transform: true | import("utility-types/dist/mapped-types")._DeepReadonlyObject<{
                process: typeof import("../../StyleSheet/processTransform").default;
            }>;
            shadowOffset: true | import("utility-types/dist/mapped-types")._DeepReadonlyObject<{
                diff: (one: any, two: any) => boolean;
            }>;
            backgroundColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderBottomColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderLeftColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderRightColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderTopColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderStartColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderEndColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            color: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            shadowColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            textDecorationColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            tintColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            textShadowColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            overlayColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
        };
    };
    RCTView: {
        removeClippedSubviews: boolean;
        pointerEvents: boolean;
        accessible: boolean;
        accessibilityActions: boolean;
        accessibilityLabel: boolean;
        accessibilityLiveRegion: boolean;
        accessibilityRole: boolean;
        accessibilityState: boolean;
        accessibilityValue: boolean;
        accessibilityHint: boolean;
        importantForAccessibility: boolean;
        nativeID: boolean;
        testID: boolean;
        renderToHardwareTextureAndroid: boolean;
        shouldRasterizeIOS: boolean;
        onLayout: boolean;
        onAccessibilityAction: boolean;
        onAccessibilityTap: boolean;
        onMagicTap: boolean;
        onAccessibilityEscape: boolean;
        collapsable: boolean;
        needsOffscreenAlphaCompositing: boolean;
        style: {
            backfaceVisibility: true;
            backgroundColor: true;
            borderColor: true;
            borderTopColor: true;
            borderRightColor: true;
            borderBottomColor: true;
            borderLeftColor: true;
            borderStartColor: true;
            borderEndColor: true;
            borderRadius: true;
            borderTopLeftRadius: true;
            borderTopRightRadius: true;
            borderTopStartRadius: true;
            borderTopEndRadius: true;
            borderBottomLeftRadius: true;
            borderBottomRightRadius: true;
            borderBottomStartRadius: true;
            borderBottomEndRadius: true;
            borderStyle: true;
            borderWidth: true;
            borderTopWidth: true;
            borderRightWidth: true;
            borderBottomWidth: true;
            borderLeftWidth: true;
            opacity: true;
            elevation: true;
            transform: true;
            transformMatrix: true;
            decomposedMatrix: true;
            scaleX: true;
            scaleY: true;
            rotation: true;
            translateX: true;
            translateY: true;
            shadowColor: true;
            shadowOffset: true;
            shadowOpacity: true;
            shadowRadius: true;
            display: true;
            width: true;
            height: true;
            start: true;
            end: true;
            top: true;
            left: true;
            right: true;
            bottom: true;
            minWidth: true;
            maxWidth: true;
            minHeight: true;
            maxHeight: true;
            margin: true;
            marginVertical: true;
            marginHorizontal: true;
            marginTop: true;
            marginBottom: true;
            marginLeft: true;
            marginRight: true;
            marginStart: true;
            marginEnd: true;
            padding: true;
            paddingVertical: true;
            paddingHorizontal: true;
            paddingTop: true;
            paddingBottom: true;
            paddingLeft: true;
            paddingRight: true;
            paddingStart: true;
            paddingEnd: true;
            borderStartWidth: true;
            borderEndWidth: true;
            position: true;
            flexDirection: true;
            flexWrap: true;
            justifyContent: true;
            alignItems: true;
            alignSelf: true;
            alignContent: true;
            overflow: true;
            flex: true;
            flexGrow: true;
            flexShrink: true;
            flexBasis: true;
            aspectRatio: true;
            zIndex: true;
            direction: true;
        } & {
            color: true;
            fontFamily: true;
            fontSize: true;
            fontStyle: true;
            fontWeight: true;
            fontVariant: true;
            textShadowOffset: true;
            textShadowRadius: true;
            textShadowColor: true;
            letterSpacing: true;
            lineHeight: true;
            textAlign: true;
            textAlignVertical: true;
            includeFontPadding: true;
            textDecorationLine: true;
            textDecorationStyle: true;
            textDecorationColor: true;
            textTransform: true;
            writingDirection: true;
            backfaceVisibility: true;
            backgroundColor: true;
            borderColor: true;
            borderTopColor: true;
            borderRightColor: true;
            borderBottomColor: true;
            borderLeftColor: true;
            borderStartColor: true;
            borderEndColor: true;
            borderRadius: true;
            borderTopLeftRadius: true;
            borderTopRightRadius: true;
            borderTopStartRadius: true;
            borderTopEndRadius: true;
            borderBottomLeftRadius: true;
            borderBottomRightRadius: true;
            borderBottomStartRadius: true;
            borderBottomEndRadius: true;
            borderStyle: true;
            borderWidth: true;
            borderTopWidth: true;
            borderRightWidth: true;
            borderBottomWidth: true;
            borderLeftWidth: true;
            opacity: true;
            elevation: true;
            transform: true;
            transformMatrix: true;
            decomposedMatrix: true;
            scaleX: true;
            scaleY: true;
            rotation: true;
            translateX: true;
            translateY: true;
            shadowColor: true;
            shadowOffset: true;
            shadowOpacity: true;
            shadowRadius: true;
            display: true;
            width: true;
            height: true;
            start: true;
            end: true;
            top: true;
            left: true;
            right: true;
            bottom: true;
            minWidth: true;
            maxWidth: true;
            minHeight: true;
            maxHeight: true;
            margin: true;
            marginVertical: true;
            marginHorizontal: true;
            marginTop: true;
            marginBottom: true;
            marginLeft: true;
            marginRight: true;
            marginStart: true;
            marginEnd: true;
            padding: true;
            paddingVertical: true;
            paddingHorizontal: true;
            paddingTop: true;
            paddingBottom: true;
            paddingLeft: true;
            paddingRight: true;
            paddingStart: true;
            paddingEnd: true;
            borderStartWidth: true;
            borderEndWidth: true;
            position: true;
            flexDirection: true;
            flexWrap: true;
            justifyContent: true;
            alignItems: true;
            alignSelf: true;
            alignContent: true;
            overflow: true;
            flex: true;
            flexGrow: true;
            flexShrink: true;
            flexBasis: true;
            aspectRatio: true;
            zIndex: true;
            direction: true;
        } & {
            resizeMode: true;
            backfaceVisibility: true;
            backgroundColor: true;
            borderColor: true;
            borderWidth: true;
            borderRadius: true;
            overflow: true;
            tintColor: true;
            opacity: true;
            overlayColor: true;
            borderTopLeftRadius: true;
            borderTopRightRadius: true;
            borderBottomLeftRadius: true;
            borderBottomRightRadius: true;
            transform: true;
            transformMatrix: true;
            decomposedMatrix: true;
            scaleX: true;
            scaleY: true;
            rotation: true;
            translateX: true;
            translateY: true;
            shadowColor: true;
            shadowOffset: true;
            shadowOpacity: true;
            shadowRadius: true;
            display: true;
            width: true;
            height: true;
            start: true;
            end: true;
            top: true;
            left: true;
            right: true;
            bottom: true;
            minWidth: true;
            maxWidth: true;
            minHeight: true;
            maxHeight: true;
            margin: true;
            marginVertical: true;
            marginHorizontal: true;
            marginTop: true;
            marginBottom: true;
            marginLeft: true;
            marginRight: true;
            marginStart: true;
            marginEnd: true;
            padding: true;
            paddingVertical: true;
            paddingHorizontal: true;
            paddingTop: true;
            paddingBottom: true;
            paddingLeft: true;
            paddingRight: true;
            paddingStart: true;
            paddingEnd: true;
            borderTopWidth: true;
            borderStartWidth: true;
            borderEndWidth: true;
            borderRightWidth: true;
            borderBottomWidth: true;
            borderLeftWidth: true;
            position: true;
            flexDirection: true;
            flexWrap: true;
            justifyContent: true;
            alignItems: true;
            alignSelf: true;
            alignContent: true;
            flex: true;
            flexGrow: true;
            flexShrink: true;
            flexBasis: true;
            aspectRatio: true;
            zIndex: true;
            direction: true;
        } & {
            transform: true | import("utility-types/dist/mapped-types")._DeepReadonlyObject<{
                process: typeof import("../../StyleSheet/processTransform").default;
            }>;
            shadowOffset: true | import("utility-types/dist/mapped-types")._DeepReadonlyObject<{
                diff: (one: any, two: any) => boolean;
            }>;
            backgroundColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderBottomColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderLeftColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderRightColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderTopColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderStartColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            borderEndColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            color: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            shadowColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            textDecorationColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            tintColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            textShadowColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
            overlayColor: true | {
                process: typeof import("../../StyleSheet/processColor").default;
            };
        };
    };
};
export default ReactNativeViewAttributes;
